name: continuos-dePloyment
run-name: Deploy do site
on:
    pull request:
        branches:
           -main
jobs:
    deploy:
        name: deploy
        runs-on: ubunto-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@4.2.2
              with:
               fetch-depth: 0

            - name: Docker login
              uses: docker/login-action@v3.4.0
              with:
                username: ${{ secrets.DOCKER_LOGIN }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Docker Build and Push
              uses: docker/build-push-action@v6.16.0
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: igorrafael9/Trab.WebSite:latest

            - name: Azure Deploy
              uses: Azure/webapps-deploy@v3.0.1
              with:
                app-name: Trab-devops-2404238
                publish-profile: ${{ secrets.PUBLISH_PROFILE }}
                image: igorrafael9/Trab.WebSite:latest

    integration-test:
        name: test-e2e
        runs-on: ubunto-latest
        needs: deploy

        steps:
            - name: Checkout repository
              uses: actions/checkout@4.2.2
              with:
                fetch-depth: 0

            - name: Setup Node j s
              uses: action/setup-node@v3.9.1
              with:
                node-version: '20'

            - name: install packages
              run: |
                cd integration-test

            