name: continous-deployment
run-name: Deploy do site
on:
    pull_request:
        branches:
            - main
jobs:
    deploy:
        name: deploy
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.2.2
              with:
                fetch-depth: 0
            
            - name: Docker login
              uses: docker/login-action@v3.4.0
              with:
                username: ${{ secrets.DOCKER_LOGIN }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: Docker Build and Push
              uses: docker/build-push-action@v6.16.0
              with:
                context: .
                file: ./Dockerfile

                push: true
                tags: igorrafael9/trab-devops:latest
            
            - name: Azure Deploy
              uses: Azure/webapps-deploy@v3.0.1
              with: 
                app-name: Trab-devops-2404238
                publish-profile: ${{ secrets.PUBLISH_PROFILE }}
                image: igorrafael9/trab-devops:latest
    
    integration-test:
        name: test-e2e
        runs-on: ubuntu-latest
        needs: deploy

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4.2.2
              with:
                fetch-depth: 0
            
            - name: Setup Nodejs
              uses: actions/setup-node@v3.9.1
              with:
                node-version: '20'
            
            - name: Install packages
              run: |
                cd test-integration
                npm install

            - name: Run Cypress E2E Test
              run: ./node_modules/.bin/cypress run
              working-directory: test-integration